export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH:/home/otis/.local/bin"


if [ "$TMUX" = "" ]; then tmux; fi


eval "$(pyenv init --path)"

# Path to your oh-my-zsh installation.
export ZSH="/home/otis/.oh-my-zsh"

# export PATH="/usr/local/cuda-11.3/bin:$PATH"
# export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"


plugins=(git pyenv docker docker-compose pipenv)
source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vi'
fi
export  EDITOR='/usr/bin/vi'
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# aliases
alias jp="jupyter notebook"
alias stc="speedtest-cli --secure"
alias tf="terraform"
alias python="python3"
alias gs="git status"
alias ga="git add"
alias gcm="git commit -m"
alias gc="git commit"
alias gd="git diff"
alias docker-compose="docker compose"
alias dc="docker compose"
alias d="docker"
alias k="kubectl"
alias mk="minikube"
alias cl="clear"
alias cr="cargo run"
alias cb="cargo build"
eval "$(pyenv init -)"

# auto complete for cli tools 
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)
[[ $commands[minikube] ]] && source <(minikube completion zsh)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# coloursied ip output automatically 
alias ip='ip -color=auto'


# colourised grep output automatically 
alias grep='grep --color=auto'


# colourised diff output automatically 
alias diff='diff --color=auto'


# colourizing man results 
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
